### PR TITLE
Add the option to choose package manager client

### PR DESCRIPTION
**Pull request by Mehdi-Hp**
I've added `readPkg.sync().ntl['package-manager']` to read the proper package manager from `package.json`. mostly because we use `yarn` in our company.

### CODE REVIEW

**Comment by farzadso** [comment]
Can we have this merged? It's a pretty good feature.

**Comment by ruyadorno** [comment]
thanks @Mehdi-Hp! 🎉 

for reference one of the things I'm going to change is that I prefer to use the `runner` analogy suggested in #43 instead of `package-manager` for the property name

keep an eye, I'll try to push a release with it later today 😊

**Comment by Mehdi-Hp** [comment]
Thanks mate 👍

**Comment by ruyadorno** [comment]
thank you so much @Mehdi-Hp 🎉 without your help I wasn't going to take a look again at this so soon 😄 

just wanted to let you know that this now landed on [v4.0.0](https://github.com/ruyadorno/ntl/releases/tag/v4.0.0) and the option is named `runner` 😊

**Comment by farzadso** [comment]
Thanks @ruyadorno

**Pull request merged**
